#
# Create new user, team, schema (with scopes) and project
# Upload a list of documents and create an annotation for the first document in the list
#

### Create new User
POST http://localhost/api/auth/signup
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "username": "{{username}}"
}

### Log in as created User

POST http://localhost/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body.token); %}

### Create Team

POST http://localhost/api/teams
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "ScopeTeam"
}
> {% client.global.set("team_id", response.body.id); %}

### Create Schema

POST http://localhost/api/schemas?
    team_id={{team_id}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

< ./scope-schema.json
> {% client.global.set("schema_id", response.body.id); %}

### Create Project

POST http://localhost/api/projects
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "ScopeProject",
  "team_id": {{team_id}},
  "schema_id": {{schema_id}}
}
> {% client.global.set("project_id", response.body.id); %}

### Import Scope documents
# @timeout 300
POST http://localhost:5001/api/documents/list?
    project_id={{project_id}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

< ./clinical-documents.json
> {% client.global.set("document_id", response.body[0].id); %}

### Create annotation

POST http://localhost/api/document_edits
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "document_id": {{document_id}}
}
> {% client.global.set("document_edit_id", response.body.id); %}

