"""empty message

Revision ID: 10337d53403c
Revises: e8813672d4ed
Create Date: 2025-05-26 09:17:18.701652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10337d53403c'
down_revision = 'e8813672d4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SchemaScope', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maximum_children_process_relevant', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commutative', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('horizontal_merging', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('vertical_merging', sa.Boolean(), nullable=True))

    with op.batch_alter_table('SchemaScopeConstraint', schema=None) as batch_op:
        batch_op.drop_column('merge_consecutive_children')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SchemaScopeConstraint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merge_consecutive_children', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('SchemaScope', schema=None) as batch_op:
        batch_op.drop_column('vertical_merging')
        batch_op.drop_column('horizontal_merging')
        batch_op.drop_column('commutative')
        batch_op.drop_column('maximum_children_process_relevant')

    # ### end Alembic commands ###
