"""empty message

Revision ID: 47279e75782c
Revises: 161b855778b7
Create Date: 2025-03-28 08:51:24.459854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47279e75782c'
down_revision = '161b855778b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SchemaScope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['Schema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SchemaScopeConstraint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schema_scope_parent_id', sa.Integer(), nullable=False),
    sa.Column('schema_scope_child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schema_scope_child_id'], ['SchemaScope.id'], ),
    sa.ForeignKeyConstraint(['schema_scope_parent_id'], ['SchemaScope.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Scope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schema_scope_id', sa.Integer(), nullable=False),
    sa.Column('document_edit_id', sa.Integer(), nullable=True),
    sa.Column('document_recommendation_id', sa.Integer(), nullable=True),
    sa.Column('token_start_id', sa.Integer(), nullable=False),
    sa.Column('token_end_id', sa.Integer(), nullable=False),
    sa.Column('parent_scope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_edit_id'], ['DocumentEdit.id'], ),
    sa.ForeignKeyConstraint(['document_recommendation_id'], ['DocumentRecommendation.id'], ),
    sa.ForeignKeyConstraint(['parent_scope_id'], ['Scope.id'], ),
    sa.ForeignKeyConstraint(['schema_scope_id'], ['SchemaScope.id'], ),
    sa.ForeignKeyConstraint(['token_end_id'], ['Token.id'], ),
    sa.ForeignKeyConstraint(['token_start_id'], ['Token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Scope')
    op.drop_table('SchemaScopeConstraint')
    op.drop_table('SchemaScope')
    # ### end Alembic commands ###
