"""empty message

Revision ID: 7f1506790b75
Revises: 47279e75782c
Create Date: 2025-04-24 14:29:54.019597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1506790b75'
down_revision = '47279e75782c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SchemaScopeConstraint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merge_consecutive_children', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SchemaScopeConstraint', schema=None) as batch_op:
        batch_op.drop_column('merge_consecutive_children')

    # ### end Alembic commands ###
