"""empty message

Revision ID: e8813672d4ed
Revises: 7f1506790b75
Create Date: 2025-05-08 17:25:33.590212

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e8813672d4ed"
down_revision = "7f1506790b75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("SchemaScope", schema=None) as batch_op:
        batch_op.add_column(sa.Column("process_relevant", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("minimum_children_process_relevant", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("SchemaScope", schema=None) as batch_op:
        batch_op.drop_column("minimum_children_process_relevant")
        batch_op.drop_column("process_relevant")

    # ### end Alembic commands ###
